CREATE DATABASE /*!32312 IF NOT EXISTS*/`db_jdbc` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `db_jdbc`;

CREATE USER 'db_jdbc'@'LOCALHOST' IDENTIFIED BY 'tpa2019';

GRANT ALL PRIVILEGES ON `db_jdbc`.* TO 'db_jdbc'@'LOCALHOST' WITH GRANT OPTION;

flush PRIVILEGES;