version: '3'

services:
  nginx:
   container_name: proxy-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - key-cloack-app
   - keycloack-platform

  key-cloack-app:
    restart: always
    build: ../keyCloack
    working_dir: /keyCloack
    volumes:
      - ../keyCloack:/keyCloack
    expose:
      - "8081"
    command: mvn clean spring-boot:run
    
  keycloack-platform:
    image: jboss/keycloak
    container_name: 'key-cloack'
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
    - KEYCLOAK_USER=keycloak_admin
    - KEYCLOAK_PASSWORD=eeX2uque
    
    
    