CREATE DATABASE /*!32312 IF NOT EXISTS*/`ml_db`;

USE `ml_db`;

CREATE USER 'ml_example'@'LOCALHOST' IDENTIFIED BY 'ml_2019';

GRANT ALL PRIVILEGES ON `ml_db`.* TO 'ml_example'@'LOCALHOST' WITH GRANT OPTION;

flush PRIVILEGES;